In [2]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\Hp\Desktop\process mining\care-flow---clinical-path-way-process-minimg\data4\hospital_process_mining_event_log-1.csv")

In [5]:
df

,case_id,activity,timestamp,department,resource
0,HOSP_0001,Patient Registration,2026-03-23 08:54:00,Front Desk,Registration Clerk
1,HOSP_0001,Initial Triage,2026-03-23 09:14:00,Emergency/Triage,Triage Nurse
2,HOSP_0001,Doctor Consultation,2026-03-23 09:19:00,Outpatient,Doctor
3,HOSP_0001,Treatment/Prescription,2026-03-23 09:40:00,Outpatient,Doctor
4,HOSP_0001,Payment Completed,2026-03-23 09:56:00,Billing,Billing Clerk
...,...,...,...,...,...
948,HOSP_0100,Initial Triage,2026-03-22 16:43:00,Emergency/Triage,Triage Nurse
949,HOSP_0100,Doctor Consultation,2026-03-22 16:47:00,Outpatient,Doctor
950,HOSP_0100,Treatment/Prescription,2026-03-22 16:55:00,Outpatient,Doctor
951,HOSP_0100,Payment Completed,2026-03-22 17:12:00,Billing,Billing Clerk
952,HOSP_0100,Patient Discharged,2026-03-22 17:28:00,Outpatient,Nurse

In [24]:
df.shape

(953, 5)

In [6]:
#cleaning

In [7]:
#go with column name 
df.columns

Index(['case_id', 'activity', 'timestamp', 'department', 'resource'], dtype='object')

In [8]:
df.columns.str.lower().str.replace("_"," ")

Index(['case id', 'activity', 'timestamp', 'department', 'resource'], dtype='object')

In [9]:
#check datatypes, null_vlaues, vlaid_data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   case_id     953 non-null    object
 1   activity    953 non-null    object
 2   timestamp   953 non-null    object
 3   department  953 non-null    object
 4   resource    953 non-null    object
dtypes: object(5)
memory usage: 37.4+ KB

In [11]:
#error in timestamp datatype, change datatype object to datetimes
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   case_id     953 non-null    object
 1   activity    953 non-null    object
 2   timestamp   953 non-null    datetime64[ns]
 3   department  953 non-null    object
 4   resource    953 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 37.4+ KB

In [14]:
#check null_values

In [15]:
df.isnull().sum()

case_id       0
activity      0
timestamp     0
department    0
resource      0
dtype: int64

In [16]:
# check duplicates

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
#sort_values

In [21]:
df[['case_id','timestamp']].sort_values(by=['case_id','timestamp'])

       case_id           timestamp
0    HOSP_0001 2026-03-23 08:54:00
1    HOSP_0001 2026-03-23 09:14:00
2    HOSP_0001 2026-03-23 09:19:00
3    HOSP_0001 2026-03-23 09:40:00
4    HOSP_0001 2026-03-23 09:56:00
..         ...                 ...
948  HOSP_0100 2026-03-22 16:43:00
949  HOSP_0100 2026-03-22 16:47:00
950  HOSP_0100 2026-03-22 16:55:00
951  HOSP_0100 2026-03-22 17:12:00
952  HOSP_0100 2026-03-22 17:28:00

[953 rows x 2 columns]

In [22]:
df

,case_id,activity,timestamp,department,resource
0,HOSP_0001,Patient Registration,2026-03-23 08:54:00,Front Desk,Registration Clerk
1,HOSP_0001,Initial Triage,2026-03-23 09:14:00,Emergency/Triage,Triage Nurse
2,HOSP_0001,Doctor Consultation,2026-03-23 09:19:00,Outpatient,Doctor
3,HOSP_0001,Treatment/Prescription,2026-03-23 09:40:00,Outpatient,Doctor
4,HOSP_0001,Payment Completed,2026-03-23 09:56:00,Billing,Billing Clerk
...,...,...,...,...,...
948,HOSP_0100,Initial Triage,2026-03-22 16:43:00,Emergency/Triage,Triage Nurse
949,HOSP_0100,Doctor Consultation,2026-03-22 16:47:00,Outpatient,Doctor
950,HOSP_0100,Treatment/Prescription,2026-03-22 16:55:00,Outpatient,Doctor
951,HOSP_0100,Payment Completed,2026-03-22 17:12:00,Billing,Billing Clerk
952,HOSP_0100,Patient Discharged,2026-03-22 17:28:00,Outpatient,Nurse